global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ai-artistic-style-service'
    metrics_path: /probe
    params:
      module: [http_post]
    static_configs:
      - targets:
          - http://ai-artistic-style:5001/styleTransfer  # Replace with your endpoint
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # Blackbox Exporter address

  - job_name: 'blackbox_exporter'
    static_configs:
      - targets:
          - blackbox-exporter:9115

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]


